In [136]:
import pandas as pd

* Series (1-dimensional):

In [137]:
Car_make = pd.Series(["BMW", "Toyota", "Honda", "Tesla", "Mercedes"])

In [138]:
Country = pd.Series(["Germany", "Japan", "Japan", "USA", "Germany"])

* DataFrames (2-dimensional):

In [139]:
car_data = pd.DataFrame({
    "Make" : Car_make,
    "Country" : Country
})

car_data

       Make  Country
0       BMW  Germany
1    Toyota    Japan
2     Honda    Japan
3     Tesla      USA
4  Mercedes  Germany

* Importing data from .csv files:

In [140]:
car_sales = pd.read_csv("car-sales.csv")

In [141]:
car_sales

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00
7   Honda   Blue          54738      4   $7,000.00
8  Toyota  White          60000      4   $6,250.00
9  Nissan  White          31600      4   $9,700.00

* Exporting a DataFrame:

In [142]:
#Exporting as .csv file:
Export_to_csv = car_sales.to_csv("Cars_data.csv")

In [143]:
#Exporting as .xlsx file:
Export_to_Xlsx = car_sales.to_excel("Cars_data.xlsx")

In [144]:
#Exporting as .csv/.xlsx without the index column:

Export_to_Xlsx_no_Index = car_sales.to_excel("Cars_data_no_Index.xlsx", index=False)

Export_to_Csv_no_Index = car_sales.to_csv("Cars_data_no_Index.csv", index=False)

In [145]:
#Reading the exported files:
Xlsx_no_Index = pd.read_excel("Cars_data_no_Index.xlsx")

Csv_no_Index = pd.read_csv("Cars_data_no_Index.csv")

In [146]:
Xlsx_no_Index

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00
7   Honda   Blue          54738      4   $7,000.00
8  Toyota  White          60000      4   $6,250.00
9  Nissan  White          31600      4   $9,700.00

In [147]:
Csv_no_Index

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00
7   Honda   Blue          54738      4   $7,000.00
8  Toyota  White          60000      4   $6,250.00
9  Nissan  White          31600      4   $9,700.00

* Note: These read copy of the csv and Excel data may look to be the same as the data with the Index (0-9) included, but when we open the .csv / Excel files saved in the project Folder, you'll notice the indexes are gone when theyr are exported as index=False.

* Exploring the Attributes of our car_sales data:

In [148]:
#The Data type Attribute (dtypes):
car_sales.dtypes

Make               str
Colour             str
Odometer (KM)    int64
Doors            int64
Price              str
dtype: object

In [149]:
#The Columns Attribute (columns):
car_sales.columns

Index(['Make', 'Colour', 'Odometer (KM)', 'Doors', 'Price'], dtype='str')

In [150]:
#The Index Attribute (index):
car_sales.index

RangeIndex(start=0, stop=10, step=1)

* Using Functions on our car-sales data:

In [151]:
#Describing the car_sales data/DataFrame (describe() function):
car_sales.describe()

       Odometer (KM)      Doors
count      10.000000  10.000000
mean    78601.400000   4.000000
std     61983.471735   0.471405
min     11179.000000   3.000000
25%     35836.250000   4.000000
50%     57369.000000   4.000000
75%     96384.500000   4.000000
max    213095.000000   5.000000

In [152]:
#The describe() function:
car_sales.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Make           10 non-null     str
 1   Colour         10 non-null     str
 2   Odometer (KM)  10 non-null     int64
 3   Doors          10 non-null     int64
 4   Price          10 non-null     str
dtypes: int64(2), str(3)
memory usage: 532.0 bytes

In [153]:
#Getting the mean (using mean() function):
car_sales.mean(numeric_only=True)

Odometer (KM)    78601.4
Doors                4.0
dtype: float64

In [154]:
#Getting the mean of a specific column (using mean() function):
car_sales["Odometer (KM)"].mean()

np.float64(78601.4)

In [155]:
#Getting the mean on a random range/series of numbers:
My_Random_range = pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
My_Random_range.mean()

np.float64(5.5)

In [156]:
#Getting the sum (using sum() function):
car_sales.sum()

Make             ToyotaHondaToyotaBMWNissanToyotaHondaHondaToyo...
Colour               WhiteRedBlueBlackWhiteGreenBlueBlueWhiteWhite
Odometer (KM)                                               786014
Doors                                                           40
Price            $4,000.00$5,000.00$7,000.00$22,000.00$3,500.00...
dtype: object

In [157]:
#...Gibberish?? 
# That's because the sum() function simply combines all the values of a non-numeric column.
# That's why we use the numeric_only=True parameter to get the sum of only the numeric columns:
car_sales.sum(numeric_only=True)

Odometer (KM)    786014
Doors                40
dtype: int64

In [158]:
#Or, we can simply do the sum of a single column which is numeric: 
car_sales["Odometer (KM)"].sum()

np.int64(786014)

* Getting the  Length (or row count) of the car_sales data:

In [159]:
len(car_sales)

10

* Viewing and Selecting data:

In [160]:
car_sales.head() #Returns the first 5 rows of the DataFrame by default.

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00

In [161]:
#In case you want more rows returned than just 5 from the top of the dataset, 
# like a Top 8 rows:
car_sales.head(8)

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00
7   Honda   Blue          54738      4   $7,000.00

In [162]:
#Getting the last 5 rows of the Dataframe (using tail() function):
car_sales.tail()

     Make Colour  Odometer (KM)  Doors      Price
5  Toyota  Green          99213      4  $4,500.00
6   Honda   Blue          45698      4  $7,500.00
7   Honda   Blue          54738      4  $7,000.00
8  Toyota  White          60000      4  $6,250.00
9  Nissan  White          31600      4  $9,700.00

In [163]:
#Or Getting the last 8:
car_sales.tail(8)

     Make Colour  Odometer (KM)  Doors       Price
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00
7   Honda   Blue          54738      4   $7,000.00
8  Toyota  White          60000      4   $6,250.00
9  Nissan  White          31600      4   $9,700.00

In [168]:
#using the function .loc (for Index location):

car_sales.loc[4] 
#.loc picks the row with index 4 (the 5th row) in the car-sales data 
# and returns it

Make                Nissan
Colour               White
Odometer (KM)       213095
Doors                    4
Price            $3,500.00
Name: 4, dtype: object

In [171]:
#but what if I changed the indexes (or index names) of each of the rows? 

My_Cars = car_sales.head(6)

My_Cars

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00

In [172]:
My_Cars.index = [0,2,4,5,4,6]

My_Cars

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
2   Honda    Red          87899      4   $5,000.00
4  Toyota   Blue          32549      3   $7,000.00
5     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
6  Toyota  Green          99213      4   $4,500.00

In [ ]:
#Returns 2 items with the same index 4 with .loc (after we changed the indexes)
My_Cars.loc[4]

     Make Colour  Odometer (KM)  Doors      Price
4  Toyota   Blue          32549      3  $7,000.00
4  Nissan  White         213095      4  $3,500.00

In [179]:
#Now we use .iloc (for Positional Index location):

My_Cars.iloc[4]

Make                Nissan
Colour               White
Odometer (KM)       213095
Doors                    4
Price            $3,500.00
Name: 4, dtype: object

In [180]:
#.iloc does not return 2 items with same index 4, but only returns 
# 'Nissan' i.e. the value which is positioned 4th in the list of My_Cars 
# if we count from 0 to 6 (0, 1, 2, 3, 4, 5, 6 where 4 is the 5th index 
# position.

* .loc refers to the Index 
* .iloc refers to the Position

* List Slicing with .iloc -

In [183]:
car_sales.iloc[:4]

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00

In [188]:
car_sales.iloc[1::4]

     Make Colour  Odometer (KM)  Doors      Price
1   Honda    Red          87899      4  $5,000.00
5  Toyota  Green          99213      4  $4,500.00
9  Nissan  White          31600      4  $9,700.00

* Selecting the Columns in a DataFrame:

In [189]:
car_sales["Make"]

0    Toyota
1     Honda
2    Toyota
3       BMW
4    Nissan
5    Toyota
6     Honda
7     Honda
8    Toyota
9    Nissan
Name: Make, dtype: str

In [ ]:
# OR 
car_sales.Make 
# (The only difference is that if the Column name has a space in it, 
# then you cannot use the dot notation (.) to access it this way)

0    Toyota
1     Honda
2    Toyota
3       BMW
4    Nissan
5    Toyota
6     Honda
7     Honda
8    Toyota
9    Nissan
Name: Make, dtype: str

for eg. if we do: 
car_sales["Odometer (KM)"], it would work fine. 

But, if we do: 
car_sales.Odometer (KM), it would Error out, because the column "Odometer (KM)" has a space in it and would not be picked in the dot (.) list

In [194]:
#Filtering the DataFrame with a condition: 

car_sales[car_sales["Odometer (KM)"] < 30000]

  Make Colour  Odometer (KM)  Doors       Price
3  BMW  Black          11179      5  $22,000.00

In [195]:
#OR lets filter for only black cars: 

Only_Black_Cars = car_sales[car_sales["Colour"] == "Black"] 

Only_Black_Cars

  Make Colour  Odometer (KM)  Doors       Price
3  BMW  Black          11179      5  $22,000.00

In [196]:
#OR only Nissans in our cars list/DF: 

Nissan_Cars = car_sales[car_sales["Make"] == "Nissan"]

Nissan_Cars

     Make Colour  Odometer (KM)  Doors      Price
4  Nissan  White         213095      4  $3,500.00
9  Nissan  White          31600      4  $9,700.00