In [384]:
import pandas as pd

* Series (1-dimensional):

In [385]:
Car_make = pd.Series(["BMW", "Toyota", "Honda", "Tesla", "Mercedes"])

In [386]:
Country = pd.Series(["Germany", "Japan", "Japan", "USA", "Germany"])

* DataFrames (2-dimensional):

In [387]:
car_data = pd.DataFrame({
    "Make" : Car_make,
    "Country" : Country
})

car_data

       Make  Country
0       BMW  Germany
1    Toyota    Japan
2     Honda    Japan
3     Tesla      USA
4  Mercedes  Germany

* Importing data from .csv files:

In [388]:
car_sales = pd.read_csv("car-sales.csv")

In [389]:
car_sales

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00
7   Honda   Blue          54738      4   $7,000.00
8  Toyota  White          60000      4   $6,250.00
9  Nissan  White          31600      4   $9,700.00

* Exporting a DataFrame:

In [390]:
#Exporting as .csv file:
Export_to_csv = car_sales.to_csv("Cars_data.csv")

In [391]:
#Exporting as .xlsx file:
Export_to_Xlsx = car_sales.to_excel("Cars_data.xlsx")

In [392]:
#Exporting as .csv/.xlsx without the index column:

Export_to_Xlsx_no_Index = car_sales.to_excel("Cars_data_no_Index.xlsx", index=False)

Export_to_Csv_no_Index = car_sales.to_csv("Cars_data_no_Index.csv", index=False)

In [393]:
#Reading the exported files:
Xlsx_no_Index = pd.read_excel("Cars_data_no_Index.xlsx")

Csv_no_Index = pd.read_csv("Cars_data_no_Index.csv")

In [394]:
Xlsx_no_Index

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00
7   Honda   Blue          54738      4   $7,000.00
8  Toyota  White          60000      4   $6,250.00
9  Nissan  White          31600      4   $9,700.00

In [395]:
Csv_no_Index

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00
7   Honda   Blue          54738      4   $7,000.00
8  Toyota  White          60000      4   $6,250.00
9  Nissan  White          31600      4   $9,700.00

* Note: These read copy of the csv and Excel data may look to be the same as the data with the Index (0-9) included, but when we open the .csv / Excel files saved in the project Folder, you'll notice the indexes are gone when theyr are exported as index=False.

* Exploring the Attributes of our car_sales data:

In [396]:
#The Data type Attribute (dtypes):
car_sales.dtypes

Make               str
Colour             str
Odometer (KM)    int64
Doors            int64
Price              str
dtype: object

In [397]:
#The Columns Attribute (columns):
car_sales.columns

Index(['Make', 'Colour', 'Odometer (KM)', 'Doors', 'Price'], dtype='str')

In [398]:
#The Index Attribute (index):
car_sales.index

RangeIndex(start=0, stop=10, step=1)

* Using Functions on our car-sales data:

In [399]:
#Describing the car_sales data/DataFrame (describe() function):
car_sales.describe()

       Odometer (KM)      Doors
count      10.000000  10.000000
mean    78601.400000   4.000000
std     61983.471735   0.471405
min     11179.000000   3.000000
25%     35836.250000   4.000000
50%     57369.000000   4.000000
75%     96384.500000   4.000000
max    213095.000000   5.000000

In [400]:
#The describe() function:
car_sales.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Make           10 non-null     str
 1   Colour         10 non-null     str
 2   Odometer (KM)  10 non-null     int64
 3   Doors          10 non-null     int64
 4   Price          10 non-null     str
dtypes: int64(2), str(3)
memory usage: 532.0 bytes

In [401]:
#Getting the mean (using mean() function):
car_sales.mean(numeric_only=True)

Odometer (KM)    78601.4
Doors                4.0
dtype: float64

In [402]:
#Getting the mean of a specific column (using mean() function):
car_sales["Odometer (KM)"].mean()

np.float64(78601.4)

In [403]:
#Getting the mean on a random range/series of numbers:
My_Random_range = pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
My_Random_range.mean()

np.float64(5.5)

In [404]:
#Getting the sum (using sum() function):
car_sales.sum()

Make             ToyotaHondaToyotaBMWNissanToyotaHondaHondaToyo...
Colour               WhiteRedBlueBlackWhiteGreenBlueBlueWhiteWhite
Odometer (KM)                                               786014
Doors                                                           40
Price            $4,000.00$5,000.00$7,000.00$22,000.00$3,500.00...
dtype: object

In [405]:
#...Gibberish?? 
# That's because the sum() function simply combines all the values of a non-numeric column.
# That's why we use the numeric_only=True parameter to get the sum of only the numeric columns:
car_sales.sum(numeric_only=True)

Odometer (KM)    786014
Doors                40
dtype: int64

In [406]:
#Or, we can simply do the sum of a single column which is numeric: 
car_sales["Odometer (KM)"].sum()

np.int64(786014)

* Getting the  Length (or row count) of the car_sales data:

In [407]:
len(car_sales)

10